# Generated by Django 4.2.4 on 2024-04-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='warehouse_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('first_price', models.CharField(max_length=255)),
                ('sale_price', models.CharField(max_length=255)),
                ('reg_data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='Images/None/no-img.jpg', upload_to='images/')),
                ('where_to', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP_Project.brand')),
            ],
        ),
        migrations.CreateModel(
            name='filial_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('filial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_Project.filial')),
                ('warehouse_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_Project.warehouse_product')),
            ],
        ),
    ]
