# Generated by Django 5.0.4 on 2024-04-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP_Project.warehouse_product'),
        ),
        migrations.AlterField(
            model_name='filial_product',
            name='filial_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP_Project.filial'),
        ),
        migrations.AlterField(
            model_name='filial_product',
            name='warehouse_product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP_Project.warehouse_product'),
        ),
    ]
