# Generated by Django 4.2.4 on 2024-04-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse_product',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='filial_product',
            old_name='count',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='warehouse_product',
            name='count',
        ),
        migrations.AddField(
            model_name='warehouse_product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
