# Generated by Django 5.0.4 on 2024-04-09 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0002_alter_warehouse_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('first_price', models.CharField(max_length=255)),
                ('sale_price', models.CharField(max_length=255)),
                ('reg_data', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='Images/None/no-img.jpg', upload_to='images/')),
                ('where_to', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
                ('brand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ERP_Project.brand')),
            ],
        ),
    ]
