# Generated by Django 5.0.4 on 2024-04-16 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERP_Project', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('cash', models.CharField(choices=[('cash', 'cash'), ('online_payment', 'online_payment')], max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ERP_Project.warehouse_product')),
            ],
        ),
    ]
